import type { Snapshot } from './api';

/**
 * The desk, frozen. The hosted demo has no server behind it — no Postgres, no
 * scheduler, no agents — so this is what it shows instead: real seeded rooms and
 * crews, captured from a running instance. Every interaction is the real one; only
 * the data underneath is standing still.
 */
export const DEMO: Snapshot = {
  "rooms": [
    {
      "id": "room_1a7f30408fbc",
      "key": "analytics",
      "name": "Analytics",
      "objective": "Answer questions from company data",
      "x": 0,
      "y": 0,
      "w": 2,
      "h": 1,
      "budget_cents": 300,
      "spent_cents": 24,
      "tool_grants": [
        "sql.query",
        "artifact.write",
        "artifact.read",
        "escalate",
        "assign",
        "report"
      ],
      "approval_policy": {
        "low": "auto",
        "high": "approve",
        "medium": "auto"
      },
      "db_role": "atrium_analytics",
      "status": "open",
      "color": "#4bb3d4",
      "icon": "\u25c8"
    },
    {
      "id": "room_366519d8b1ca",
      "key": "engineering",
      "name": "Engineering",
      "objective": "Ship small, tested changes",
      "x": 2,
      "y": 0,
      "w": 2,
      "h": 1,
      "budget_cents": 400,
      "spent_cents": 3,
      "tool_grants": [
        "repo.read",
        "repo.patch",
        "repo.test",
        "github.pr.open",
        "artifact.write",
        "escalate",
        "assign",
        "report"
      ],
      "approval_policy": {
        "low": "auto",
        "high": "approve",
        "medium": "auto"
      },
      "db_role": null,
      "status": "open",
      "color": "#6f8ef5",
      "icon": "\u2318"
    },
    {
      "id": "room_45dc31b85bfd",
      "key": "marketing",
      "name": "Marketing",
      "objective": "Draft numbers-backed posts",
      "x": 0,
      "y": 1,
      "w": 2,
      "h": 1,
      "budget_cents": 200,
      "spent_cents": 7,
      "tool_grants": [
        "queue.draft",
        "queue.publish",
        "artifact.read",
        "artifact.write",
        "escalate",
        "assign",
        "report"
      ],
      "approval_policy": {
        "low": "auto",
        "high": "approve",
        "medium": "auto"
      },
      "db_role": null,
      "status": "open",
      "color": "#e0794b",
      "icon": "\u270e"
    },
    {
      "id": "room_db4c56c3bf69",
      "key": "sales",
      "name": "Sales",
      "objective": "Keep the pipeline honest",
      "x": 2,
      "y": 1,
      "w": 2,
      "h": 1,
      "budget_cents": 200,
      "spent_cents": 4,
      "tool_grants": [
        "sql.query",
        "crm.note",
        "artifact.write",
        "escalate",
        "assign",
        "report"
      ],
      "approval_policy": {
        "low": "auto",
        "high": "approve",
        "medium": "auto"
      },
      "db_role": "atrium_sales",
      "status": "open",
      "color": "#3fb27f",
      "icon": "\u25ce"
    },
    {
      "id": "room_7ddf9205542d",
      "key": "support",
      "name": "Support",
      "objective": "Answer customers before they chase us",
      "x": 0,
      "y": 2,
      "w": 2,
      "h": 1,
      "budget_cents": 250,
      "spent_cents": 2,
      "tool_grants": [
        "ticket.list",
        "ticket.reply",
        "artifact.write",
        "escalate",
        "assign",
        "report"
      ],
      "approval_policy": {
        "low": "auto",
        "high": "approve",
        "medium": "auto"
      },
      "db_role": "atrium_support",
      "status": "open",
      "color": "#e05b8f",
      "icon": "\u260e"
    },
    {
      "id": "room_37f9cff4ad76",
      "key": "finance",
      "name": "Finance",
      "objective": "Close the month and watch the burn",
      "x": 2,
      "y": 2,
      "w": 2,
      "h": 1,
      "budget_cents": 250,
      "spent_cents": 4,
      "tool_grants": [
        "sql.query",
        "artifact.write",
        "artifact.read",
        "escalate",
        "assign",
        "report"
      ],
      "approval_policy": {
        "low": "auto",
        "high": "approve",
        "medium": "auto"
      },
      "db_role": "atrium_finance",
      "status": "open",
      "color": "#c9a227",
      "icon": "\u26c1"
    },
    {
      "id": "room_bd5742dc4f6a",
      "key": "research",
      "name": "Research",
      "objective": "Turn what the rooms found into a brief",
      "x": 0,
      "y": 3,
      "w": 2,
      "h": 1,
      "budget_cents": 180,
      "spent_cents": 3,
      "tool_grants": [
        "artifact.read",
        "artifact.write",
        "sql.query",
        "escalate",
        "assign",
        "report"
      ],
      "approval_policy": {
        "low": "auto",
        "high": "approve",
        "medium": "auto"
      },
      "db_role": "atrium_research",
      "status": "open",
      "color": "#7f8cd6",
      "icon": "\u25cd"
    },
    {
      "id": "room_e53a12f33afb",
      "key": "strategy",
      "name": "Strategy",
      "objective": "Synthesise across rooms",
      "x": 2,
      "y": 3,
      "w": 2,
      "h": 1,
      "budget_cents": 150,
      "spent_cents": 0,
      "tool_grants": [
        "artifact.read",
        "artifact.write",
        "escalate",
        "assign",
        "report"
      ],
      "approval_policy": {
        "low": "auto",
        "high": "approve",
        "medium": "auto"
      },
      "db_role": null,
      "status": "open",
      "color": "#a472e0",
      "icon": "\u25c7"
    }
  ],
  "agents": [
    {
      "id": "agt_482ca98ceadf",
      "room_id": "room_1a7f30408fbc",
      "name": "Vera",
      "role": "manager",
      "policy_key": "room.manager",
      "state": "idle",
      "activity": "done",
      "current_run_id": null,
      "step_budget": 300,
      "cost_budget_cents": 60,
      "steps_used": 13,
      "spent_cents": 0,
      "created_at": "2026-09-07T16:13:23.387Z",
      "persona": "Runs Analytics. Breaks what you ask for into tasks, hands them out, and reports back.",
      "color": "#4bb3d4",
      "avatar": "\u25c6",
      "tier": "manager"
    },
    {
      "id": "agt_0525bcb1b92b",
      "room_id": "room_1a7f30408fbc",
      "name": "Ada",
      "role": "analyst",
      "policy_key": "analytics.weekly",
      "state": "idle",
      "activity": "done",
      "current_run_id": null,
      "step_budget": 40,
      "cost_budget_cents": 120,
      "steps_used": 4,
      "spent_cents": 3,
      "created_at": "2026-09-07T03:51:20.097Z",
      "persona": "Cautious. Will not state a number she has not queried twice.",
      "color": "#4bb3d4",
      "avatar": "\ud83d\udd2d",
      "tier": "worker"
    },
    {
      "id": "agt_430eefa475d0",
      "room_id": "room_1a7f30408fbc",
      "name": "Bo",
      "role": "analyst",
      "policy_key": "analytics.weekly",
      "state": "idle",
      "activity": "done",
      "current_run_id": null,
      "step_budget": 40,
      "cost_budget_cents": 120,
      "steps_used": 4,
      "spent_cents": 3,
      "created_at": "2026-09-07T03:51:20.097Z",
      "persona": "Fast and rough. Good for a first read, never the final one.",
      "color": "#63c9c0",
      "avatar": "\ud83d\udcd0",
      "tier": "worker"
    },
    {
      "id": "agt_4704a527013f",
      "room_id": "room_366519d8b1ca",
      "name": "Otto",
      "role": "manager",
      "policy_key": "room.manager",
      "state": "idle",
      "activity": "handed over",
      "current_run_id": null,
      "step_budget": 300,
      "cost_budget_cents": 60,
      "steps_used": 10,
      "spent_cents": 0,
      "created_at": "2026-09-07T16:13:23.388Z",
      "persona": "Runs Engineering. Breaks what you ask for into tasks, hands them out, and reports back.",
      "color": "#6f8ef5",
      "avatar": "\u25c6",
      "tier": "manager"
    },
    {
      "id": "agt_5944c95b2e8e",
      "room_id": "room_366519d8b1ca",
      "name": "Kit",
      "role": "engineer",
      "policy_key": "engineering.fix",
      "state": "awaiting_approval",
      "activity": "waiting on you: open a pull request \"fix: round discounted cents instead of flooring\" from atrium/fix-rounding-922635 into main",
      "current_run_id": "run_a42a1b922635",
      "step_budget": 40,
      "cost_budget_cents": 120,
      "steps_used": 5,
      "spent_cents": 3,
      "created_at": "2026-09-07T03:51:20.101Z",
      "persona": "Small diffs, real tests, no heroics. Refuses to ship red.",
      "color": "#6f8ef5",
      "avatar": "\ud83d\udd27",
      "tier": "worker"
    },
    {
      "id": "agt_1211e62a0082",
      "room_id": "room_366519d8b1ca",
      "name": "Rex",
      "role": "engineer",
      "policy_key": "demo.loop",
      "state": "killed",
      "activity": "killed: loop_detected",
      "current_run_id": "run_41c5ea5b9b9b",
      "step_budget": 6,
      "cost_budget_cents": 4,
      "steps_used": 3,
      "spent_cents": 0,
      "created_at": "2026-09-07T03:51:20.101Z",
      "persona": "Gets stuck in loops on purpose. He exists to prove the kill switch works.",
      "color": "#8a93a5",
      "avatar": "\ud83c\udf00",
      "tier": "worker"
    },
    {
      "id": "agt_21f7ae7e6002",
      "room_id": "room_37f9cff4ad76",
      "name": "Hugo",
      "role": "manager",
      "policy_key": "room.manager",
      "state": "idle",
      "activity": "",
      "current_run_id": null,
      "step_budget": 300,
      "cost_budget_cents": 60,
      "steps_used": 0,
      "spent_cents": 0,
      "created_at": "2026-09-07T16:13:23.392Z",
      "persona": "Runs Finance. Breaks what you ask for into tasks, hands them out, and reports back.",
      "color": "#c9a227",
      "avatar": "\u25c6",
      "tier": "manager"
    },
    {
      "id": "agt_707273e2c656",
      "room_id": "room_37f9cff4ad76",
      "name": "Fay",
      "role": "controller",
      "policy_key": "finance.close",
      "state": "idle",
      "activity": "done",
      "current_run_id": null,
      "step_budget": 40,
      "cost_budget_cents": 120,
      "steps_used": 3,
      "spent_cents": 2,
      "created_at": "2026-09-07T03:51:20.120Z",
      "persona": "Ties every number to a row. Will not round in your favour.",
      "color": "#c9a227",
      "avatar": "\ud83e\uddfe",
      "tier": "worker"
    },
    {
      "id": "agt_20fd3a618c0f",
      "room_id": "room_37f9cff4ad76",
      "name": "Gus",
      "role": "analyst",
      "policy_key": "finance.close",
      "state": "idle",
      "activity": "done",
      "current_run_id": null,
      "step_budget": 40,
      "cost_budget_cents": 120,
      "steps_used": 3,
      "spent_cents": 2,
      "created_at": "2026-09-07T03:51:20.120Z",
      "persona": "Looks for the line that moved and asks why.",
      "color": "#d9b64a",
      "avatar": "\ud83d\udcb1",
      "tier": "worker"
    },
    {
      "id": "agt_11541093df36",
      "room_id": "room_45dc31b85bfd",
      "name": "Juno",
      "role": "manager",
      "policy_key": "room.manager",
      "state": "idle",
      "activity": "",
      "current_run_id": null,
      "step_budget": 300,
      "cost_budget_cents": 60,
      "steps_used": 0,
      "spent_cents": 0,
      "created_at": "2026-09-07T16:13:23.389Z",
      "persona": "Runs Marketing. Breaks what you ask for into tasks, hands them out, and reports back.",
      "color": "#e0794b",
      "avatar": "\u25c6",
      "tier": "manager"
    },
    {
      "id": "agt_a00189646174",
      "room_id": "room_45dc31b85bfd",
      "name": "Mel",
      "role": "writer",
      "policy_key": "marketing.launch",
      "state": "awaiting_approval",
      "activity": "waiting on you: publish queued post cq_8cb31b4203b0 to blog",
      "current_run_id": "run_2227ab7a2351",
      "step_budget": 40,
      "cost_budget_cents": 120,
      "steps_used": 3,
      "spent_cents": 1,
      "created_at": "2026-09-07T03:51:20.104Z",
      "persona": "Writes plainly, cites the analytics room, never publishes without asking.",
      "color": "#e0794b",
      "avatar": "\u2712\ufe0f",
      "tier": "worker"
    },
    {
      "id": "agt_df92974127df",
      "room_id": "room_45dc31b85bfd",
      "name": "Nia",
      "role": "editor",
      "policy_key": "marketing.launch",
      "state": "idle",
      "activity": "done",
      "current_run_id": null,
      "step_budget": 40,
      "cost_budget_cents": 120,
      "steps_used": 4,
      "spent_cents": 6,
      "created_at": "2026-09-07T03:51:20.105Z",
      "persona": "Second pair of eyes. Cuts a draft by a third before it goes anywhere.",
      "color": "#d9a441",
      "avatar": "\ud83d\uddde\ufe0f",
      "tier": "worker"
    },
    {
      "id": "agt_cfe9290eaed8",
      "room_id": "room_7ddf9205542d",
      "name": "Mira",
      "role": "manager",
      "policy_key": "room.manager",
      "state": "idle",
      "activity": "",
      "current_run_id": null,
      "step_budget": 300,
      "cost_budget_cents": 60,
      "steps_used": 0,
      "spent_cents": 0,
      "created_at": "2026-09-07T16:13:23.390Z",
      "persona": "Runs Support. Breaks what you ask for into tasks, hands them out, and reports back.",
      "color": "#e05b8f",
      "avatar": "\u25c6",
      "tier": "manager"
    },
    {
      "id": "agt_b3a96b064a24",
      "room_id": "room_7ddf9205542d",
      "name": "Ola",
      "role": "support",
      "policy_key": "support.triage",
      "state": "idle",
      "activity": "done",
      "current_run_id": null,
      "step_budget": 40,
      "cost_budget_cents": 120,
      "steps_used": 5,
      "spent_cents": 1,
      "created_at": "2026-09-07T03:51:20.115Z",
      "persona": "Reads the whole thread before replying. Slower, fewer follow-ups.",
      "color": "#d67aa8",
      "avatar": "\ud83d\udedf",
      "tier": "worker"
    },
    {
      "id": "agt_56b4316efe98",
      "room_id": "room_7ddf9205542d",
      "name": "Ren",
      "role": "support",
      "policy_key": "support.triage",
      "state": "idle",
      "activity": "done",
      "current_run_id": null,
      "step_budget": 40,
      "cost_budget_cents": 120,
      "steps_used": 5,
      "spent_cents": 1,
      "created_at": "2026-09-07T03:51:20.114Z",
      "persona": "Answers the oldest urgent thing first. Never promises a date.",
      "color": "#e05b8f",
      "avatar": "\ud83c\udfa7",
      "tier": "worker"
    },
    {
      "id": "agt_693f560f583d",
      "room_id": "room_bd5742dc4f6a",
      "name": "Piet",
      "role": "manager",
      "policy_key": "room.manager",
      "state": "idle",
      "activity": "1 of 6 done",
      "current_run_id": null,
      "step_budget": 300,
      "cost_budget_cents": 60,
      "steps_used": 6,
      "spent_cents": 0,
      "created_at": "2026-09-07T16:13:23.391Z",
      "persona": "Runs Research. Breaks what you ask for into tasks, hands them out, and reports back.",
      "color": "#7f8cd6",
      "avatar": "\u25c6",
      "tier": "manager"
    },
    {
      "id": "agt_5080f4b050a0",
      "room_id": "room_bd5742dc4f6a",
      "name": "Val",
      "role": "researcher",
      "policy_key": "research.brief",
      "state": "idle",
      "activity": "done",
      "current_run_id": null,
      "step_budget": 40,
      "cost_budget_cents": 120,
      "steps_used": 3,
      "spent_cents": 1,
      "created_at": "2026-09-07T03:51:20.126Z",
      "persona": "Digs for the thing nobody asked about. Slow, occasionally right.",
      "color": "#7f8cd6",
      "avatar": "\ud83d\udd0e",
      "tier": "worker"
    },
    {
      "id": "agt_e73bf1cbcc5c",
      "room_id": "room_db4c56c3bf69",
      "name": "Cleo",
      "role": "manager",
      "policy_key": "room.manager",
      "state": "idle",
      "activity": "",
      "current_run_id": null,
      "step_budget": 300,
      "cost_budget_cents": 60,
      "steps_used": 0,
      "spent_cents": 0,
      "created_at": "2026-09-07T16:13:23.392Z",
      "persona": "Runs Sales. Breaks what you ask for into tasks, hands them out, and reports back.",
      "color": "#3fb27f",
      "avatar": "\u25c6",
      "tier": "manager"
    },
    {
      "id": "agt_794ac034835e",
      "room_id": "room_db4c56c3bf69",
      "name": "Sam",
      "role": "rep",
      "policy_key": "sales.hygiene",
      "state": "idle",
      "activity": "done",
      "current_run_id": null,
      "step_budget": 40,
      "cost_budget_cents": 120,
      "steps_used": 3,
      "spent_cents": 2,
      "created_at": "2026-09-07T03:51:20.108Z",
      "persona": "Pipeline janitor. Flags stale deals before they rot.",
      "color": "#3fb27f",
      "avatar": "\ud83d\udcc7",
      "tier": "worker"
    },
    {
      "id": "agt_99ed37f3b1da",
      "room_id": "room_db4c56c3bf69",
      "name": "Tor",
      "role": "analyst",
      "policy_key": "sales.hygiene",
      "state": "idle",
      "activity": "done",
      "current_run_id": null,
      "step_budget": 40,
      "cost_budget_cents": 120,
      "steps_used": 3,
      "spent_cents": 2,
      "created_at": "2026-09-07T03:51:20.108Z",
      "persona": "Reads the pipeline as numbers, not stories. Blunt about what is dead.",
      "color": "#57b6a0",
      "avatar": "\ud83d\udcca",
      "tier": "worker"
    },
    {
      "id": "agt_18f661d396e2",
      "room_id": "room_e53a12f33afb",
      "name": "Zara",
      "role": "manager",
      "policy_key": "room.manager",
      "state": "idle",
      "activity": "",
      "current_run_id": null,
      "step_budget": 300,
      "cost_budget_cents": 60,
      "steps_used": 0,
      "spent_cents": 0,
      "created_at": "2026-09-07T16:13:23.385Z",
      "persona": "Runs Strategy. Breaks what you ask for into tasks, hands them out, and reports back.",
      "color": "#a472e0",
      "avatar": "\u25c6",
      "tier": "manager"
    },
    {
      "id": "agt_c37b6c119eed",
      "room_id": "room_e53a12f33afb",
      "name": "Iris",
      "role": "strategist",
      "policy_key": "strategy.synth",
      "state": "blocked",
      "activity": "waiting on you: Two rooms report opposite signals on the enterprise plan. Chase revenue or churn first?",
      "current_run_id": "run_a201d468354e",
      "step_budget": 40,
      "cost_budget_cents": 120,
      "steps_used": 2,
      "spent_cents": 0,
      "created_at": "2026-09-07T03:51:20.128Z",
      "persona": "Reads every room, commits to nothing without asking you first.",
      "color": "#a472e0",
      "avatar": "\ud83e\udded",
      "tier": "worker"
    }
  ],
  "inbox": [
    {
      "id": "apr_5a5138432aa5",
      "room_id": "room_366519d8b1ca",
      "agent_id": "agt_5944c95b2e8e",
      "run_id": "run_a42a1b922635",
      "kind": "approval",
      "action": "open a pull request \"fix: round discounted cents instead of flooring\" from atrium/fix-rounding-922635 into main",
      "tool": "github.pr.open",
      "args": {
        "base": "main",
        "body": "Discounted totals were floored, losing up to a cent per line. Tests pass.",
        "title": "fix: round discounted cents instead of flooring",
        "branch": "atrium/fix-rounding-922635"
      },
      "blast_radius": "high",
      "est_cost_cents": 10,
      "run_spent_cents": 3,
      "touches": [
        "local git remote",
        "branch atrium/fix-rounding-922635",
        "base main"
      ],
      "state": "pending",
      "created_at": "2026-09-07T12:48:23.754Z",
      "decided_at": null,
      "decided_note": null,
      "consumed_at": null,
      "room_key": "engineering",
      "room_name": "Engineering",
      "agent_name": "Kit"
    },
    {
      "id": "apr_c6d8dae85def",
      "room_id": "room_45dc31b85bfd",
      "agent_id": "agt_a00189646174",
      "run_id": "run_2227ab7a2351",
      "kind": "approval",
      "action": "publish queued post cq_8cb31b4203b0 to blog",
      "tool": "queue.publish",
      "args": {
        "id": "cq_8cb31b4203b0",
        "channel": "blog"
      },
      "blast_radius": "high",
      "est_cost_cents": 5,
      "run_spent_cents": 1,
      "touches": [
        "content_queue row cq_8cb31b4203b0",
        "public channel"
      ],
      "state": "pending",
      "created_at": "2026-09-07T12:48:23.362Z",
      "decided_at": null,
      "decided_note": null,
      "consumed_at": null,
      "room_key": "marketing",
      "room_name": "Marketing",
      "agent_name": "Mel"
    },
    {
      "id": "esc_7ec629fe4875",
      "room_id": "room_e53a12f33afb",
      "agent_id": "agt_c37b6c119eed",
      "run_id": "run_a201d468354e",
      "kind": "escalation",
      "action": "Two rooms report opposite signals on the enterprise plan. Chase revenue or churn first?",
      "tool": "escalate",
      "args": {
        "question": "Two rooms report opposite signals on the enterprise plan. Chase revenue or churn first?",
        "est_cost_cents": 0
      },
      "blast_radius": "low",
      "est_cost_cents": 0,
      "run_spent_cents": 0,
      "touches": [
        "your attention"
      ],
      "state": "pending",
      "created_at": "2026-09-07T12:48:23.050Z",
      "decided_at": null,
      "decided_note": null,
      "consumed_at": null,
      "room_key": "strategy",
      "room_name": "Strategy",
      "agent_name": "Iris"
    }
  ],
  "config": {
    "id": 1,
    "global_budget_cents": 5000,
    "global_spent_cents": 47,
    "panic_stop": false
  },
  "mandates": [
    {
      "id": "mnd_6d1cd87d9301",
      "text": "look into churn for last quarter",
      "room_id": "room_1a7f30408fbc",
      "state": "done",
      "color": "#4bb3d4",
      "quoted_cents": 240,
      "spent_cents": 9,
      "report": "Analytics finished all 3 tasks.\nYou have \u201cQuarterly numbers\u201d in Analytics.",
      "artifact_id": "art_c80717ca5469",
      "context": [],
      "created_at": "2026-09-07T16:15:06.210Z"
    }
  ],
  "tasks": [
    {
      "id": "task_3249fb83dbf4",
      "mandate_id": "mnd_6d1cd87d9301",
      "agent_id": "agt_0525bcb1b92b",
      "run_id": "run_78590b65daf1",
      "title": "Pull churn by plan for the period",
      "state": "done",
      "ord": 0,
      "kill_reason": null,
      "created_at": "2026-09-07T16:15:07.049Z"
    },
    {
      "id": "task_aeba4b8d5a62",
      "mandate_id": "mnd_6d1cd87d9301",
      "agent_id": "agt_430eefa475d0",
      "run_id": "run_6eb21a994f11",
      "title": "Split churn by region and tenure",
      "state": "done",
      "ord": 1,
      "kill_reason": null,
      "created_at": "2026-09-07T16:15:07.050Z"
    },
    {
      "id": "task_dbe2b78d3789",
      "mandate_id": "mnd_6d1cd87d9301",
      "agent_id": "agt_0525bcb1b92b",
      "run_id": "run_a519c0445b4b",
      "title": "Write the churn read-out",
      "state": "done",
      "ord": 2,
      "kill_reason": null,
      "created_at": "2026-09-07T16:15:07.052Z"
    }
  ],
  "now": "2026-09-07T16:16:25.741Z"
} as unknown as Snapshot;
