/**
 * Writes the service worker after a build, with the precache list baked in.
 *
 * Generated rather than hand-written because the list has to name the hashed files vite
 * just emitted, and a stale list is worse than none: it would serve last build's shell
 * for ever. Run from `npm -w web run build`.
 */
import { readdirSync, statSync, writeFileSync, readFileSync } from 'node:fs';
import { join, relative } from 'node:path';

const DIST = new URL('../web/dist/', import.meta.url).pathname;

const walk = (dir) => readdirSync(dir).flatMap((name) => {
  const p = join(dir, name);
  return statSync(p).isDirectory() ? walk(p) : [p];
});

const files = walk(DIST)
  .map((p) => '/' + relative(DIST, p))
  .filter((p) => !p.endsWith('/sw.js') && !p.endsWith('.map'));

// The shell is what a cold start must have before it can paint anything at all. The
// rest — the lazily-loaded apps, the demo snapshot — is fetched on demand and kept.
const SHELL = files.filter((p) =>
  p === '/index.html' || p === '/manifest.webmanifest' ||
  /^\/assets\/index-.*\.(js|css)$/.test(p) ||
  /^\/fonts\/google-sans-latin\.woff2$/.test(p));

// Any change to a shipped file changes this, which is what evicts the old caches.
const version = readFileSync(new URL('../web/dist/index.html', import.meta.url), 'utf8')
  .match(/assets\/index-([\w-]+)\.js/)?.[1] ?? String(files.length);

writeFileSync(join(DIST, 'sw.js'), `/* generated by scripts/sw.mjs — do not edit */
const V = ${JSON.stringify(version)};
const SHELL = ${JSON.stringify(SHELL)};
const CACHE = 'atrium-' + V;

self.addEventListener('install', (e) => {
  e.waitUntil(caches.open(CACHE).then((c) => c.addAll(SHELL)).then(() => self.skipWaiting()));
});

self.addEventListener('activate', (e) => {
  e.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim()));
});

self.addEventListener('fetch', (e) => {
  const req = e.request;
  if (req.method !== 'GET') return;
  const url = new URL(req.url);
  if (url.origin !== location.origin) return;

  // Live state is never cached. Serving yesterday's agents from disk would be a lie,
  // and the stream must not be intercepted at all.
  if (url.pathname.startsWith('/api/')) return;

  // Hashed assets are immutable: if it is in the cache it is the right one, for ever.
  if (/\\/assets\\/.*-[\\w-]{8,}\\.(js|css)$/.test(url.pathname) || url.pathname.startsWith('/fonts/')) {
    e.respondWith(caches.match(req).then((hit) => hit ?? fetch(req).then((res) => {
      if (res.ok) { const copy = res.clone(); caches.open(CACHE).then((c) => c.put(req, copy)); }
      return res;
    })));
    return;
  }

  // The shell is network-first, and that is not a preference.
  //
  // It names this build's hashed assets. Answering a navigation from cache would hand a
  // returning visitor the *previous* build's HTML, whose asset URLs no longer exist on
  // the deploy they just landed on — a blank page, with no way out but a hard reload
  // they do not know to do. So: try the network, fall back to cache only when offline.
  e.respondWith((async () => {
    const cache = await caches.open(CACHE);
    const key = req.mode === 'navigate' ? '/index.html' : req;
    try {
      const res = await fetch(req);
      if (res.ok) cache.put(key, res.clone());
      return res;
    } catch {
      return (await cache.match(key)) ?? Response.error();
    }
  })());
});
`);

console.log(`sw.js — ${SHELL.length} shell files precached, version ${version}`);
